services:
  app-portfolio:
    build:
      context: ./app-portafolio
    ports:
      - 3000:3000
    image: willyabad/portafolio:1.0.0
    volumes:
      - /home/nimbux/logs/app-portafolio:/logs
    container_name: app-portafolio
    networks:
      - portafolio-network

networks:
  portfolio-network:
    driver: bridge
